version: '3'
services:
  server1:
    container_name: server2
    image: server2:latest
    stdin_open: true
    tty: true
    environment:
      - DOCKERHOST=${DOCKERHOST}
      - IP=${IP}
    ports:
      - "7000:7000"
    restart: always
    cap_drop:
      - ALL